[package]
name = "clamor_hashmap"
version = "1.3.1"  #:version

[lib]
crate-type = ["cdylib"]      # Creates dynamic lib

# For Clamor.
[dependencies.rsmalloc]
path = "../rsmalloc"
optional = true

[features]
clamor = ["rsmalloc"]