[package]
name = "clamor_ps"
version = "1.3.1"  #:version

[lib]
crate-type = ["cdylib"]      # Creates dynamic lib

[dependencies]
libc="*"
rand="*"

# For Clamor.
[dependencies.rsmalloc]
path = "../rsmalloc"
